name: scannercp-server


services:

  # ==========================================================
  # MYSQL
  # ==========================================================

  mysql:

    image: mysql:8.4

    restart: unless-stopped

    environment:

      MYSQL_ROOT_PASSWORD: ${MYSQL_ROOT_PASSWORD}

      MYSQL_DATABASE: ${MYSQL_DATABASE}

      MYSQL_USER: ${MYSQL_USER}

      MYSQL_PASSWORD: ${MYSQL_PASSWORD}


    volumes:

      - mysql_data:/var/lib/mysql


    healthcheck:

      test:
        [
          "CMD-SHELL",
          "mysqladmin ping -h localhost -u root -p$$MYSQL_ROOT_PASSWORD || exit 1"
        ]

      interval: 10s

      timeout: 5s

      retries: 10

      start_period: 30s


    networks:

      - scannercp-network



  # ==========================================================
  # SPRING BOOT
  # ==========================================================

  app:

    build:

      context: .

      dockerfile: Dockerfile


    restart: unless-stopped


    environment:

      SERVER_PORT: 8080

      SPRING_DATASOURCE_URL: jdbc:mysql://mysql:3306/${MYSQL_DATABASE}

      SPRING_DATASOURCE_USERNAME: ${MYSQL_USER}

      SPRING_DATASOURCE_PASSWORD: ${MYSQL_PASSWORD}


    depends_on:

      mysql:

        condition: service_healthy


    ports:

      - "8080:8080"


    networks:

      - scannercp-network



  # ==========================================================
  # TAILSCALE TUNNEL
  # ==========================================================

  tailscale:

    image: tailscale/tailscale:latest

    restart: unless-stopped

    environment:

      TS_AUTHKEY: ${TAILSCALE_AUTH_KEY}

      TS_STATE_DIR: /var/lib/tailscale

      TS_AUTH_ONCE: "true"

      TS_HOSTNAME: scannercp


    volumes:

      - tailscale_state:/var/lib/tailscale


    network_mode: "service:app"


    depends_on:

      - app



# ============================================================
# VOLUMEN
# ============================================================

volumes:

  mysql_data:

    external: true

    name: scannercp_mysql_data

  tailscale_state:



# ============================================================
# RED
# ============================================================

networks:

  scannercp-network:

    driver: bridge