spring.application.name=web

spring.thymeleaf.cache=false

# ===============================
# MYSQL
# ===============================

spring.datasource.url=${SPRING_DATASOURCE_URL:jdbc:mysql://mysql:3306/pruebaweb}
spring.datasource.username=${MYSQL_USER}
spring.datasource.password=${MYSQL_PASSWORD}
spring.datasource.driver-class-name=com.mysql.cj.jdbc.Driver


# ===============================
# JPA / HIBERNATE
# ===============================

spring.jpa.hibernate.ddl-auto=validate
spring.jpa.show-sql=true