spring.application.name=scannercp
spring.port=${PORT:8080}
spring.thymeleaf.cache=false

# ===============================
# MYSQL
# ===============================

spring.datasource.url=${SPRING_DATASOURCE_URL:jdbc:mysql://mysql:3306/scannercp_db}

spring.datasource.username=${SPRING_DATASOURCE_USERNAME:scannercp}

spring.datasource.password=${SPRING_DATASOURCE_PASSWORD:scannerpc}
spring.datasource.driver-class-name=com.mysql.cj.jdbc.Driver


# ===============================
# JPA / HIBERNATE
# ===============================

spring.jpa.hibernate.ddl-auto=validate
spring.jpa.show-sql=true

#===============================
# FLYWAY
#===============================
spring.flyway.enabled=true
spring.flyway.locations=classpath:db/migration

